[package]
name = "chorus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bovidae = "0.2.3"
lexify = "0.1.6"
fnv = "1.0.3"
itertools = "0.9"
